---
# file: roles/common/tasks/main.yml

- name: upgrade all packages
  yum: name=* state=latest

- name: Install the common packages
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - git
    - which
    - tar
    - vi

- name: Download confd binary
  get_url: url=https://github.com/kelseyhightower/confd/releases/download/v0.3.0/confd_0.3.0_linux_amd64.tar.gz dest=/tmp/confd_0.3.0_linux_amd64.tar.gz mode=0440